# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"display_frames": "00_core.ipynb",
         "display_in_cols": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://vochicong.github.io/pandas_show/"

git_url = "https://github.com/vochicong/pandas_show/tree/master/"

def custom_doc_links(name): return None
